-- ============================================================================
-- Validation client du releve mensuel (periode 26 -> 25) avant facturation
-- Base : WALLIS-LABEL (tfmnmzyetybaeygughcs) - PAS Cortex
-- ============================================================================
-- 1. chantiers.email_contact : destinataire de la demande de validation
-- 2. table validations_recap_mensuel : une ligne par (chantier, periode)
--    statuts : brouillon -> envoye -> valide | refuse -> facture
--    snapshot jsonb = detail par jour FIGE a l'envoi (preuve de ce que le
--    client a valide) : { lignes: [{date, machines, metrage, heures, attente}],
--    totaux: {metrage, heures, attente} }
-- 3. RLS : utilisateurs de l'app (app_users) uniquement ; la page publique
--    valider.html passe par les endpoints Vercel en service role (bypass RLS),
--    l'anonyme n'a AUCUN acces direct a la table.
-- ============================================================================

-- ─── 1. Email du contact client par chantier ───
alter table public.chantiers add column if not exists email_contact text;

-- ─── 2. Table des validations mensuelles ───
create table if not exists public.validations_recap_mensuel (
  id bigint generated by default as identity primary key,
  chantier_id bigint not null references public.chantiers(id) on delete cascade,
  periode_debut date not null,          -- le 26 du mois precedent
  periode_fin date not null,            -- le 25 du mois
  libelle text,                         -- ex. "Periode du 26/06/2026 au 25/07/2026"
  token uuid not null default gen_random_uuid(),
  destinataire_email text,
  statut text not null default 'brouillon'
    check (statut in ('brouillon', 'envoye', 'valide', 'refuse', 'facture')),
  snapshot jsonb,
  sent_at timestamptz,
  relance_at timestamptz,
  validated_at timestamptz,
  validataire_nom text,
  validataire_email text,
  signature_png text,
  commentaire_refus text,
  -- Corrections proposees par le client, UNE entree PAR VALEUR modifiee :
  -- [{date, champ (metrage|heures|attente), avant, apres, commentaire}]
  corrections jsonb,
  facture_envoyee_at timestamptz,
  created_at timestamptz not null default now(),
  unique (chantier_id, periode_debut)
);

-- Si la table existait deja (re-execution) : ajout idempotent de la colonne
alter table public.validations_recap_mensuel add column if not exists corrections jsonb;

create index if not exists idx_vrm_token on public.validations_recap_mensuel (token);
create index if not exists idx_vrm_statut on public.validations_recap_mensuel (statut);

-- ─── 3. RLS ───
-- LECTURE SEULE pour les utilisateurs de l'app : cette table est la PREUVE qui
-- debloque la facturation. Toutes les ECRITURES passent par les endpoints
-- Vercel en service role (send-validation-recap / validation-recap / cron),
-- jamais par le front. Aucune policy anon (table invisible aux non-connectes).
alter table public.validations_recap_mensuel enable row level security;

drop policy if exists "vrm_app_users_all" on public.validations_recap_mensuel;
drop policy if exists "vrm_app_users_select" on public.validations_recap_mensuel;
create policy "vrm_app_users_select" on public.validations_recap_mensuel
  for select to authenticated
  using (exists (
    select 1 from public.app_users u
    where lower(u.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  ));

-- ─── 4. Realtime (l'onglet admin se met a jour tout seul) ───
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public'
      and tablename = 'validations_recap_mensuel'
  ) then
    alter publication supabase_realtime add table public.validations_recap_mensuel;
  end if;
end $$;

-- ─── 5. Verification ───
select column_name from information_schema.columns
where table_name = 'validations_recap_mensuel' order by ordinal_position;
