-- ============================================================================
-- Releves kilometrage du parc automobile (saisie APP Employes)
-- Base : WALLIS-LABEL (tfmnmzyetybaeygughcs) - PAS Cortex
-- ============================================================================
-- 1. Table releves_km : un releve de compteur par (vehicule, date, saisie)
-- 2. Trigger : synchronise equipements.km_actuel avec le MAX des releves du
--    vehicule (best effort : ne bloque jamais la saisie terrain si la mise a
--    jour echoue). La fiche vehicule admin, les entretiens au km et le
--    controle technique profitent donc automatiquement des releves.
-- ============================================================================

-- ─── 1. Table ───
create table if not exists public.releves_km (
  id bigint generated by default as identity primary key,
  vehicule_code text not null,              -- immatriculation (comme consommations_carburant.sondeuse_code)
  date_releve date not null,
  kilometrage numeric not null check (kilometrage > 0),
  sondeur_id bigint,                        -- hash du code personnel (meme convention que les autres tables)
  sondeur_nom text,
  created_at timestamptz not null default now()
);

create index if not exists idx_releves_km_veh on public.releves_km (vehicule_code, date_releve desc);

-- ─── 2. RLS (memes acces que consommations_carburant : app employes + admin) ───
alter table public.releves_km enable row level security;

drop policy if exists "releves_km_select" on public.releves_km;
create policy "releves_km_select" on public.releves_km
  for select to anon, authenticated using (true);

drop policy if exists "releves_km_insert" on public.releves_km;
create policy "releves_km_insert" on public.releves_km
  for insert to anon, authenticated with check (true);

drop policy if exists "releves_km_delete" on public.releves_km;
create policy "releves_km_delete" on public.releves_km
  for delete to anon, authenticated using (true);

-- ─── 3. Sync equipements.km_actuel (best effort, jamais bloquant) ───
create or replace function public.sync_km_actuel_releve()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_max numeric;
begin
  if tg_op = 'DELETE' then v_code := old.vehicule_code; else v_code := new.vehicule_code; end if;
  v_code := upper(trim(coalesce(v_code, '')));
  if v_code = '' then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;
  begin
    select max(kilometrage) into v_max
      from public.releves_km
     where upper(trim(vehicule_code)) = v_code;
    if coalesce(v_max, 0) > 0 then
      update public.equipements e
         set km_actuel = v_max
       where upper(trim(coalesce(e.immatriculation, ''))) = v_code
         and lower(coalesce(e.categorie, '')) = 'vl'
         and coalesce(e.km_actuel, 0) <> v_max;
    end if;
  exception when others then
    -- On ne bloque JAMAIS l'enregistrement du releve pour un souci de sync
    raise notice 'sync km_actuel ignoree : %', sqlerrm;
  end;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists trg_sync_km_actuel on public.releves_km;
create trigger trg_sync_km_actuel
  after insert or update or delete on public.releves_km
  for each row execute function public.sync_km_actuel_releve();

-- ─── 4. Verification ───
select column_name from information_schema.columns
where table_name = 'releves_km' order by ordinal_position;
